GET {{API_URL}}/api/report/1dc1817e-511f-434c-88bd-8a286c136988

POST {{API_URL}}/api/report
Content-Type: application/json

{
	"description": "This is my report type",
	"type": "bug"
}


POST {{API_URL}}/api/report
Content-Type: application/json

{
	"title":"split node",
	"description": "Please add a split node",
	"type": "feat",
	"labels": ["UI","Nodes"]
}


PUT {{API_URL}}/api/report/1dc1817e-511f-434c-88bd-8a286c136988
Content-Type: application/json

{
  "labels": ["UI", "Nodes"]
}

DEL {{API_URL}}/api/report
